- name: run hello app
  docker: image=hanswesterbeek/hello ports=8080 name=hello

- name: Display IP address and port mappings for containers
  debug: msg={{inventory_hostname}}:{{item['HostConfig']['PortBindings']['8080/tcp'][0]['HostPort']}}
  with_items: docker_containers
